version: '3.9'
services:

  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "10.0.0.2:80:80"
      - "10.0.0.2:8000:8000"
      - "10.0.0.2:3000:3000"
      - "10.0.0.2:443:443"

  postgresql:
    image: postgres:12.0
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pvlsazrmhjejwthkvrhlncwxuk
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'

  backend:
    container_name: api
    build: ./backend
    depends_on:
      - postgresql
    command: >
      sh -c " python manage.py makemigrations --settings=settings.settings &&
              python manage.py migrate --settings=settings.settings &&
              python manage.py collectstatic --settings=settings.settings --noinput &&
              gunicorn settings.asgi:application --env DJANGO_SETTINGS_MODULE=settings.settings -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media

  frontend:
    container_name: frontend
    build: ./frontend

volumes:
  media_volume:
  static_volume: