version: '3'
services:

  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend
    volumes:
      - static_volume:/root/kibtop/services/backend/staticfiles
      - media_volume:/root/kibtop/services/backend/media
    ports:
      - "80:80"
      - "443:443"

  postgresql:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: api
    command: >
      sh -c " python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn settings.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/root/kibtop/services/backend/staticfiles
      - media_volume:/root/kibtop/services/backend/media
    depends_on:
      - postgresql
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    command: >
      sh -c "npm run dev"
    depends_on:
      - postgresql
    ports:
      - "3000:3000"

volumes:
  postgres_volume:
  static_volume:
  media_volume: