version: "3.9"

services:
   react:
         container_name: react
         restart: on-failure
         build: .
         volumes:
              - ./src:/app/src
         ports:
              - "3000:3000"
         command: >
              sh -c "yarn start"